version: '3.6'

services:
  scoop:
    image: microsoft/windowsservercore:1803
    container_name: scoop_debug
    command: powershell.exe -NoLogo -NoExit
    working_dir: C:\SCOOP\apps\scoop\current\bin
    environment:
      SCOOP: C:\SCOOP
      SCOOP_HOME: C:\SCOOP\apps\scoop\current
    volumes:
      - .:C:\SCOOP\apps\scoop\current
